/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'TW100/TW100',
  //   // {
  //   //   type: 'category',
  //   //   label: 'TW100',
  //   //   items: ['TW100/TW100'],
  //   // },
  //   {
  //     type: 'category',
  //     label: 'TW100',
  //     items: [
  //       {
  //         type: 'doc',
  //         id: 'doc2',
  //       },
  //       {
  //         type: 'doc',
  //         id: 'doc3',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'link',
  //     label: 'Learn more',
  //     href: 'https://example.com',
  //   },    
  // ],
};

export default sidebars;
